variables:
- group: ProductsApiDev
- name: apiName
  value: productsapi  
- name: environmentName
  value: dev    
- name: rgName
  value: "rg-$(apiName)-$(environmentName)"
- name: rgLocation
  value: Australia Southeast  
- name: sharedRgName
  value: rg-shared-$(environmentName)
- name: planSku
  value: "S1"
- name: planCapacity
  value: 1  
- name: aspNetCoreEnvironment
  value: Development
- name: webSiteTimeZone
  value: AUS Eastern Standard Time  
- name: serverName
  value: "sql-$(apiName)-$(environmentName)"
- name: databaseName
  value: "sqldb-$(apiName)-$(environmentName)"  
- name: adminUserName
  value: "admin-$(apiName)-$(environmentName)"
- name: sharedRgLocation
  value: Australia Southeast    
- name: sharedStorageName
  value: "sg$(apiName)$(environmentName)"
- name: sharedContainerName
  value: "armtemplates"  
- name: "SomeConfiguration.SomeSetting"
  value: "123456"