steps:
  - task: AzureResourceManagerTemplateDeployment@3    
    displayName: 'Create app service plan'
    inputs:
      deploymentScope: 'Resource Group' 
      azureResourceManagerConnection: '$(azureSubscription)' 
      location: '$(rgLocation)' 
      action: 'Create Or Update Resource Group' 
      resourceGroupName: '$(rgName)'
      deploymentMode: 'Incremental' 
      csmFile: '$(Pipeline.Workspace)/deploy/AppServicePlan/template.json' 
      csmParametersFile: '$(Pipeline.Workspace)/deploy/AppServicePlan/template.parameters.json' 
      overrideParameters: |
        -planName "plan-$(apiName)-$(environmentName)" 
        -planLocation "$(rgLocation)" 
        -sku "$(planSku)" 
        -capacity "$(planCapacity)" 
      