steps:
  - task: AzureResourceManagerTemplateDeployment@3    
    displayName: 'Create resource group'
    inputs:
      deploymentScope: 'Subscription'
      azureResourceManagerConnection: '$(azureSubscription)'            
      location: '$(rgLocation)'                    
      deploymentMode: 'Incremental'
      csmFile: '$(Pipeline.Workspace)/deploy/ResourceGroup/template.json'
      csmParametersFile: '$(Pipeline.Workspace)/deploy/ResourceGroup/template.parameters.json'
      overrideParameters: |
        -rgName "$(rgName)" 
        -rgLocation "$(rgLocation)" 