steps:
  - task: AzureRmWebAppDeployment@3
    displayName: 'Deploy to Staging'
    inputs:
      azureSubscription: '$(azureSubscription)'
      WebAppName: '$(apiName)'
      DeployToSlotFlag: true
      ResourceGroupName: '$(rgName)'
      SlotName: staging
      Package: '$(Pipeline.Workspace)/WebApp/MyShop.ProductManagement.Api.zip'
      ScriptType: 'Inline Script'
      enableXmlVariableSubstitution: true

  - task: AzureAppServiceManage@0
    displayName: 'Start Staging Slot'
    inputs:
      azureSubscription: '$(azureSubscription)' 
      action: 'Start Azure App Service'
      webAppName: '$(apiName)'
      specifySlotOrASE: true
      resourceGroupName: '$(rgName)'
      slot: staging

  - task: AzureAppServiceManage@0
    displayName: 'Swap to Production'    
    inputs:
      azureSubscription: '$(azureSubscription)'
      webAppName: '$(apiName)'
      resourceGroupName: '$(rgName)'
      sourceSlot: staging

  - task: AzureAppServiceManage@0
    displayName: 'Stop Staging Slot'    
    inputs:
      azureSubscription: '$(azureSubscription)'
      action: 'Stop Azure App Service'
      webAppName: '$(apiName)'
      specifySlotOrASE: true
      resourceGroupName: '$(rgName)'
      slot: staging
      