steps:
  - task: AzureResourceManagerTemplateDeployment@3    
    displayName: 'Create key vault'
    inputs:
      deploymentScope: 'Resource Group' 
      azureResourceManagerConnection: '$(azureSubscription)' 
      location: '$(rgLocation)' 
      action: 'Create Or Update Resource Group' 
      resourceGroupName: '$(rgName)'
      deploymentMode: 'Incremental' 
      csmFile: '$(Pipeline.Workspace)/deploy/KeyVault/template.json' 
      csmParametersFile: '$(Pipeline.Workspace)/deploy/KeyVault/template.parameters.json' 
      overrideParameters: |
        -keyVaultName "kv-$(apiName)-$(environmentName)" 
        -keyVaultLocation "$(rgLocation)" 
        -apiName "app-$(apiName)-$(environmentName)" 
        -sqlServerConnectionString "the secure connection string"
      