steps:

  # - task: UseDotNet@2
  #   inputs:
  #     version: '5.0.x'
  #     performMultiLevelLookup: true
  #     includePreviewVersions: true # Required for preview versions

  - task: DotNetCoreCLI@2
    displayName: 'Build $(platformConfiguration)'
    inputs:
      command: "build"
      # arguments: '--configuration $(BuildConfiguration)'
      projects: '**/*.csproj'

  - task: DotNetCoreCLI@2
    displayName: Test
    inputs:
      command: 'test'
      projects: '**/*Tests.csproj'
      arguments: '--configuration Release'      

  - task: DotNetCoreCLI@2
    displayName: "Dotnet Publish"
    inputs:
      command: "publish"
      publishWebProjects: true
      arguments: "--configuration $(platformConfiguration) --output $(Build.ArtifactStagingDirectory)"
      zipAfterPublish: True

  - task: PublishBuildArtifacts@1
    displayName: "Publish Build Artifact"
    inputs:
      pathtoPublish: "$(Build.ArtifactStagingDirectory)"
      artifactName: "WebApp"

  - task: PublishBuildArtifacts@1
    displayName: "Copy ARM Templates"
    inputs:
      pathtoPublish: $(Build.Repository.LocalPath)/Deploy/Resources
      artifactName: "deploy"

  - task: DotNetCoreCLI@2
    inputs:
      command: publish 
      arguments: -r win-x64 -p:PublishSingleFile=True --self-contained false -o $(Build.ArtifactStagingDirectory)
      projects: '**/MyShop.ProductManagement.DbSetup.csproj'
      publishWebProjects: false
      zipAfterPublish: False
    enabled: true  

  - task: PublishBuildArtifacts@1
    displayName: "Publish Console App"
    inputs:
      pathtoPublish: "$(Build.ArtifactStagingDirectory)/MyShop.ProductManagement.DbSetup/MyShop.ProductManagement.DbSetup.exe"
      artifactName: "DbConsoleApp"              