steps:

  - task: UseDotNet@2
    inputs:
      version: '5.0.x'
      performMultiLevelLookup: true
      includePreviewVersions: true # Required for preview versions

  - task: DotNetCoreCLI@2
    displayName: 'Build $(buildConfiguration)'
    inputs:
      command: "build"
      arguments: '--configuration $(buildConfiguration)'
      projects: '**/*.csproj'

  - task: DotNetCoreCLI@2
    displayName: Test
    inputs:
      command: 'test'
      projects: '**/*Tests.csproj'
      arguments: '--configuration Release'      

  - task: DotNetCoreCLI@2
    displayName: "Dotnet Publish"
    inputs:
      command: "publish"
      publishWebProjects: true
      arguments: "--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)"
      zipAfterPublish: True

  - task: PublishBuildArtifacts@1
    displayName: "Publish Build Artifact"
    inputs:
      pathtoPublish: "$(Build.ArtifactStagingDirectory)"
      artifactName: "WebApp"

  - task: PublishBuildArtifacts@1
    displayName: "Copy ARM Templates"
    inputs:
      pathtoPublish: $(Build.Repository.LocalPath)/Deploy/Resources
      artifactName: "deploy"      