steps:

- template: 'Steps/deployResourceGroup.yaml'
- template: 'Steps/deployAppServicePlan.yaml'
- template: 'Steps/deployWebApi.yaml'
- template: 'Steps/deployCode.yaml'
- template: 'Steps/deploySqlServerAndDatabase.yaml'